### ISSUE TITLE
No City Info at Character Creation on ML Client

### ISSUE THREAD

**Issue by Djeryv** [Pack4Duck/ClassicUO#1479]
When you create a character in the ML client, the city information won't display. It does with the High Seas client though.

![image](https://user-images.githubusercontent.com/49735284/149183932-e4dde80b-ae92-4b05-89b8-ad726f70f2fd.png)

**Comment by gaechti** [comment]
whats the client version?

from what I get:
if client version is lower 7.0.13 it reads from citytext.enu file, is that file present?

https://github.com/ClassicUO/ClassicUO/blob/e41559baf7fd61476e5803ee900516779a12474f/src/Game/Scenes/LoginScene.cs#L746

I tested with 7.0.8.3 and it works fine, if the citytext.enu file is not present, its empty like you reported.

seems to be an issue on your end
