### ISSUE TITLE
Field over Field

### ISSUE THREAD

**Issue by canerksk** [Pack4Duck/ClassicUO#1480]
**Describe the bug**
Applying the WallOfStone spell through the spellbook,
Then, when we cast a macro with CastSpell: WallOfStone + LastTarget, it applies the first spell, but when we press the macro for the second use spell, it does not apply the spell because it perceives it as an object, not an ground.

**To Reproduce**
1. Open Spellbook and extract wallofstone spell
2. Wallofstone spell using manuel apply
3. Create a WallofStone + LastTarget (eg f1 key)
4. Press F1 using spell of WallofStone
5. Second time press f1 "You can't seen the target" message

**Shard**
 - Local:

**Information (please complete the following information):**
 - OS: Windows 10 Pro 2H21 - IS Build: 19043.1466 Windows Feature Experience Pack 120.2212.3920.0
 - ClassicUO Version:  0.1.10.0
 - [NO]
 - Launcher: None
 - Assistant: None, Native ClassicUO Client

Note:
I solved this problem by making some changes under case MacroType.LastTarget: in MacroManager.cs, but I am aware that this is not a complete solution. What could be the exact solution for this?

Change i made;

```
 case MacroType.LastTarget:

if (TargetManager.IsTargeting)
{
  if (TargetManager.TargetingState != CursorTarget.Object)
  {
 TargetManager.TargetLast();
// this line was added by me.
  //GameActions.Say("Object Target");
  TargetManager.Target(TargetManager.LastTargetInfo.Graphic, TargetManager.LastTargetInfo.X, TargetManager.LastTargetInfo.Y, TargetManager.LastTargetInfo.Z); 
 }
....
```

this is how it works now, but I don't know if this could cause other problems in other variations.

**Edit: above solution didn't work.**

**Comment by andreakarasho** [comment]
When you cast WoS you target the ground, so the ground will be your lasttarget.
If the wall still over the tile and you re-run the macro the tile is covered by the wall casted before. 
I see nothing wrong tbh.

**Comment by canerksk** [comment]
You cannot assign a field 3 times in a row.  It hits 2 times but says you can't reach the 3rd target
