### ISSUE TITLE
PandoraUO broken items

### ISSUE THREAD

**Issue by SkylerPixel** [Pack4Duck/ClassicUO#1482]
On PandoraUO the Master Runebook and soulforge do not bring up their respective menus.

**To reproduce the error**
1. Login to PandoraUO with CalssicUO
2. Attempt to open a Master Runebook or soulforge

**Expected behavior**
The menus display and function as intended

**Shard**
 - Name of the shard: PandoraUO

**Information (please complete the following information):**
 - OS: Windows11
 - ClassicUO Version: Latest from ClassicUO website as of writing
 - Launcher: ClassicAssist

**Additional context**
 - The items seem to work on Beta 0.1.8.0 and break on Beta 0.1.9.0+
 - There seems to be a [previous issue](https://github.com/ClassicUO/ClassicUO/issues/1045) on this topic where it was fixed before breaking again

**Comment by andreakarasho** [comment]
not cuo related I guess
