### ISSUE TITLE
skill increase-decrease does not show skill change message if change is less than 1%

### ISSUE THREAD

**Issue by acid-beast** [Pack4Duck/ClassicUO#1484]
as per summary, problem in src/Network/PacketHandlers.cs 

if (change != 0.0f && !float.IsNaN(change) && ProfileManager.CurrentProfile != null && ProfileManager.CurrentProfile.ShowSkillsChangedMessage && Math.Abs(change) >= ProfileManager.CurrentProfile.ShowSkillsChangedDeltaValue)

change is float, usually 0.1
when ShowSkillsChangedDeltaValue is int = 1 in profile.cs

public int ShowSkillsChangedDeltaValue { get; set; } = 1;

so when skill is changed less than 1%, change message is not shown
usually skill is changed by 0.1% - so I can say that skill change message is never shown in real live gameplay.

**Comment by rsuperior** [comment]
ShowSkillsChangedDeltaValue is only 1 _by default_.

If you want to see those 0.1 skill changes, you're meant to use the slider labeled 'Inform when skills change by' to 0 under the 'General' section of the Options menu, like so.  This will change the value of ShowSkillsChangedDeltaValue.

![image](https://user-images.githubusercontent.com/97489744/149703506-e74d5ee1-f46d-4ba9-906d-1df03234fd4d.png)

You can definitely ask about stuff like this in Discord if you run into anything else you find surprising.

**Comment by roxya** [comment]
The standard client has a 0-1000 slider for 0.1% precision, I think it makes sense to change ClassicUO to have the same precision. 1% isn't terribly useful

**Comment by roxya** [comment]
Change made https://github.com/ClassicUO/ClassicUO/commit/22c6882178005b7a47fbfdbb653d553407846262
