### ISSUE TITLE
Keep Runebook Open

### ISSUE THREAD

**Issue by chris-ux** [Pack4Duck/ClassicUO#1491]
**Describe the bug**
When using spells from the rune's page, gate or recall, the runebook will close every time.

I wish for runebook to stay open, in case of fail.  It is more of a pain to reopen runebook, then reopen correct page, then recast than it is to manually close the runebook on success.

**To Reproduce**
1. Open Runebook
2. Open a page with a rune
3. Try to use the icon to cast either gate or recall
4. See book close automatically.

**Expected behavior**
Runebook stays open.

**Screenshots**
unnecessary

**Shard**
 - Any free shard i've tried.  UO Renaissance, Angel Island.

**Information (please complete the following information):**
 - OS: win10
 - ClassicUO Version: any but mine is 0.1.9.31
 - [ ] Using DEV Version? no
 - Launcher: [classicuo_launcher, uof launcher, ...] Renaissance Launcher, Angel Island Launcher

**Comment by markdwags** [comment]
That behavior is handled by the server, not the client. Looking at the default RunUO code at least, I don't see where it re-sends the gump after you recall or gate.

I do see where "Set Default" resends the gump, and I confirmed clicking that does in fact resend the runebook gump in CUO.

**Comment by chris-ux** [comment]
Cool, was hoping it would be an easy enhancement. Bummer.

Thanks for looking into it!

**Comment by chris-ux** [comment]
> That behavior is handled by the server, not the client. Looking at the default RunUO code at least, I don't see where it re-sends the gump after you recall or gate.
> 
> I do see where "Set Default" resends the gump, and I confirmed clicking that does in fact resend the runebook gump in CUO.

Bummer.  Was hoping it would be an easy enhancement.  Thanks for looking into it!
