### ISSUE TITLE
TextFileParser skips final token if it's a single-character, and is EOL (EOF)

### ISSUE THREAD

**Issue by roxya** [Pack4Duck/ClassicUO#1498]
This is quite minor.

If the final line of my text file is:
```
40 BDFFD6 A A E
```
"E" is the end of line character.

https://github.com/ClassicUO/ClassicUO/blob/a4e7f1d01eb40dcf2c4aff8a45749a410b89bbb1/src/Utility/TextFileParser.cs#L272-L275

This dictates that it will be skipped. Asking for token[4] will give an index out of range exception.

Workaround: Include a new line at the end of the file so that \n is the EOL

**Comment by andreakarasho** [comment]
Texting from mobile so im going to write a quick answer.
The GetEOL function check for \n and for the eof.
In both cases the code set the _eol variable to the current position “i”. This is wrong when hitting the eof because we skip the last char. Instead when hitting eof we need to put _eol = i +1.

**Comment by roxya** [comment]
Tried it and it seems good, thanks!

https://github.com/ClassicUO/ClassicUO/commit/b245b05fd5213d1b21ec6818875ea83ec4dc6726
