### ISSUE TITLE
ClassicUOLauncher.app fails on Mac M1

### ISSUE THREAD

**Issue by kjkeefe** [Pack4Duck/ClassicUO#1501]
When trying to launch the ClassicUOLauncher.app on a Mac machine that uses the new M1 chip, it quits unexpectedly (see attached image). 

The full problem details and system configuration text is in the attached text file. 

[classicuolauncher-full-report.txt](https://github.com/ClassicUO/ClassicUO/files/8113127/classicuolauncher-full-report.txt)
![classicuolauncher-quit-unexpectedly](https://user-images.githubusercontent.com/13408406/155050390-efc3029e-cc96-4dcc-a571-078d77e0328e.png)

**Comment by andreakarasho** [comment]
Cuolauncher is built against bigsur on a x64 cpu. Will not work on an m1 chip
