### ISSUE TITLE
[Regression] A character wearing a certain combination of items shows completely naked after relogin

### ISSUE THREAD

**Issue by Agetian** [Pack4Duck/ClassicUO#1538]
**Describe the bug**
Tested this on Ultima Adventures, a heavily customized fork of Ultima Odyssey running on RunUO 2.2 base and client 7.0.15.1:
https://www.servuo.com/threads/ultima-adventures-a-full-featured-content-packed-offline-online-server.12503/page-29#post-82585

On the latest dev branch, if a character wears both a robe and a cloak and logs out, then after the next log in the character will be shown completely naked (both on the actual playfield and on the paperdoll), with no ability to undress anything or put anything on into the slots that are already occupied. Interestingly, if an admin character logs in and grabs the character with "[admin" ("Get" function), then the character will be shown fully dressed, but if you log in as the said character itself again, it'll once again be shown naked.

On the latest released beta (0.1.10 from October 2021), this works fine and does not cause the nudity glitch.

**To Reproduce**
1. Make sure the latest ClassicUO dev is used (I used the latest update identified as 0.1.10.255 when installing through the ClassicUO Launcher). I don't know if this makes any difference, but I'm running on Linux via Mono.
2. On Ultima Adventures, dress an ordinary (non-admin/non-GM) character in such a way that it wears a robe and a cloak together. My test characters also always wore something on their legs and chest, which may or may not matter (e.g. a shirt).
3. Log out, then log in with the same account and characfer.
4. Your character will show completely naked, with no possibility of undressing the existing (but not visualized) items or dressing anything else.

**Expected behavior**
The character should not be stark naked and should be correctly shown with all the clothes on :)
This is the correct behavior observed in beta 0.1.10.

**Screenshots**
Here's the comparison of the same character visualized in 0.1.10 Beta and in 0.1.10.255 Dev:
![Снимок экрана от 2022-06-04 22-20-09](https://user-images.githubusercontent.com/24357441/172022650-8a4f872d-f12a-41e0-88d1-a2913d87336d.png)

![Снимок экрана от 2022-06-04 22-22-07](https://user-images.githubusercontent.com/24357441/172022645-5c940734-3388-4180-8f94-998aea2f8238.png)

**Shard**
Ultima Adventures

**Information (please complete the following information):**
 - OS: Linux Mint 20.3
 - ClassicUO Version: 0.1.10.255 (latest dev update through ClassicUO Launcher)
 - [X] Using DEV Version?
 - Launcher: ClassicUO Launcher

**Additional context**
 - Only one client is running in parallel.
 - Screen Resolution: 1920x1080

**Comment by Agetian** [comment]
Interestingly, it seems like it's something particular about robes more so than about cloaks - even if the cloak is removed (per the screenshots above), it doesn't fix the issue until the robe is undressed. If the robe is removed, the character starts showing normally in 0.1.10.255.

**Comment by Agetian** [comment]
Ok, some more testing on this: it looks like the problem may have to do with the fact that the current version of ClassicUO dev allows incompatible items to be worn, which causes issues after a relogin or something like that. It doesn't even necessarily have to do with a robe and a cloak combination in particular. For example:

If my character is wearing this combination of items, it'll show stark naked and can only be undressed via the Razor undress button:
![изображение](https://user-images.githubusercontent.com/24357441/172034461-736034ae-dc22-4e2b-8970-848c1665e568.png)

If after undressing, I wear all of these items *except* the torch, everything will be fine. However, as soon as I add the torch to the mix and then relogin, the character will be naked. Apparently, it's because both hands and the spellbook are equipped at the same time in this case. If I equip a spellbook *or* the torch, everything works as desired.

**Comment by Agetian** [comment]
Another possible lead: if this issue happens, I see this message in the console log repeated multiple times (I don't see it if the game is running without the issue triggered):
06/05/2022 03:57:30 |   Error    | Texture not found in paperdoll: gump_graphic: 60000

**Comment by andreakarasho** [comment]
I  wonder if it’s related to this: https://github.com/ClassicUO/ClassicUO/commit/74aead9f45f2518b1ca852097e8f2335fc2234b9

**Comment by Agetian** [comment]
Hmm, not sure, I wanted to try compiling without the commit you referenced, but sadly, ClassicUO won't compile for me for some silly reason and I can't figure out why. I can test this if there's an archive of older builds available somewhere (or if I figure out how to compile, hehe)

**Comment by Agetian** [comment]
Fixed upstream, closing the issue.
