### ISSUE TITLE
Cloning project not able to download some of the externals

### ISSUE THREAD

**Issue by Crystal1462** [Pack4Duck/ClassicUO#1539]
Using this command:
git clone --recursive https://github.com/ClassicUO/ClassicUO.git
It downloads all of your project but not the external and provides this error:

Cloning into 'C:/Development/ClassicUO/ClassicUO/external/FNA/lib/FAudio'...
fatal: unable to connect to github.com:
github.com[0: 140.82.112.3]: errno=Unknown error

fatal: clone of 'git://github.com/FNA-XNA/FAudio.git' into submodule path 'C:/Development/ClassicUO/ClassicUO/external/FNA/lib/FAudio' failed
Failed to clone 'lib/FAudio'. Retry scheduled
Cloning into 'C:/Development/ClassicUO/ClassicUO/external/FNA/lib/FNA3D'...
fatal: unable to connect to github.com:
github.com[0: 140.82.112.3]: errno=Unknown error

fatal: clone of 'git://github.com/FNA-XNA/FNA3D.git' into submodule path 'C:/Development/ClassicUO/ClassicUO/external/FNA/lib/FNA3D' failed
Failed to clone 'lib/FNA3D'. Retry scheduled
Cloning into 'C:/Development/ClassicUO/ClassicUO/external/FNA/lib/SDL2-CS'...
fatal: unable to connect to github.com:
github.com[0: 140.82.113.3]: errno=Unknown error

fatal: clone of 'git://github.com/flibitijibibo/SDL2-CS.git' into submodule path 'C:/Development/ClassicUO/ClassicUO/external/FNA/lib/SDL2-CS' failed
Failed to clone 'lib/SDL2-CS'. Retry scheduled
Cloning into 'C:/Development/ClassicUO/ClassicUO/external/FNA/lib/Theorafile'...
fatal: unable to connect to github.com:
github.com[0: 140.82.113.3]: errno=Unknown error

fatal: clone of 'git://github.com/FNA-XNA/Theorafile.git' into submodule path 'C:/Development/ClassicUO/ClassicUO/external/FNA/lib/Theorafile' failed
Failed to clone 'lib/Theorafile'. Retry scheduled
Cloning into 'C:/Development/ClassicUO/ClassicUO/external/FNA/lib/FAudio'...
fatal: unable to connect to github.com:
github.com[0: 140.82.114.4]: errno=Unknown error

fatal: clone of 'git://github.com/FNA-XNA/FAudio.git' into submodule path 'C:/Development/ClassicUO/ClassicUO/external/FNA/lib/FAudio' failed
Failed to clone 'lib/FAudio' a second time, aborting
Submodule path 'external/MP3Sharp': checked out '652104fbac52b92810f96c2a091f70ccdbd25a91'
Failed to recurse into submodule path 'external/FNA'

Systems 
Windows 10
Visual Studio 2019 (Never made it that far but just in case)

Thanks in advance

**Comment by gaechti** [comment]
maybe there is an easyer way, but this worked for me:
1: git clone --recursive https://github.com/ClassicUO/ClassicUO.git
2: cd ClassicUO
3: git checkout dev
4: git submodule update --init --recursive --force
5: cd external/FNA
6: edit .gitmodules file with editor (in external/FNA) and replace git: with https:
7: git submodule sync
8: git submodule update --init --recursive --force
9: cd lib/FNA3D/
10: edit .gitmodules file with editor (in external/FNA/lib/FNA3D) and replace git: with https:
11: git submodule sync
12: git submodule update --init --recursive --force

**Comment by Crystal1462** [comment]
Thank you, just in case someone reads this in the future this same process will need to be done in a few of the FNA external links as well but it will work out in the end :)

**Comment by DemonRok** [comment]
> 5: cd external/FNA
> 6: edit .gitmodules file with editor (in external/FNA) and replace git: with https:
> 7: git submodule sync
> 8: git submodule update --init --recursive --force

After 8: the content of .gitmodules in external/FNA came back to git: and fail again for me

**Comment by gaechti** [comment]
> > 5: cd external/FNA
> > 6: edit .gitmodules file with editor (in external/FNA) and replace git: with https:
> > 7: git submodule sync
> > 8: git submodule update --init --recursive --force
> 
> After 8: the content of .gitmodules in external/FNA came back to git: and fail again for me

pretty sure you did not cd into external/FNA folder (step 5)

**Comment by Crystal1462** [comment]
Closing the issue as this does solve the problem
