### ISSUE TITLE
Bodyconv.def and anim3.mul problem

### ISSUE THREAD

**Issue by DemonRok** [Pack4Duck/ClassicUO#1543]
I have difficulty in making CU work with my Bodyconv.def, if with the client I use (4.0.0c), the animations are correctly displayed, with CU the monsters are not displayed at all. Even using an original anim3.mul, the same thing happens. Has anyone had this kind of problem before?
Thanks in advance.

client 4.0.0c:
![Client](https://user-images.githubusercontent.com/57641759/182243678-8f7c9a88-afb9-4f1f-90af-8ff088fe3b33.png)
ClassicUO:
![Client-CU](https://user-images.githubusercontent.com/57641759/182243758-3755ceea-db7a-46fa-ad90-f1584b150029.png)

**Comment by andreakarasho** [comment]
fixed https://github.com/ClassicUO/ClassicUO/commit/eb6ffc068dd296aa41ffbf972d1c37f2690607d3
