### ISSUE TITLE
How to close the log console screen

### ISSUE THREAD

**Issue by Crystal1462** [Pack4Duck/ClassicUO#1561]
**Describe the bug**
Pretty sure this comes under "Lack of User Knowledge" and not a bug but there isn't a better place to ask that I am aware of.

Trying to figure out how to run the client without the log console opening up as well, this functionality is present within the official launcher for ClassicUO.  Is there a setting some where?

Pretty east to duplicate, I just compile and run (Debug or Release versions)  Hopefully this is clear enough and if not, will grab a screenshot.

Thanks in advance.

**Comment by roxya** [comment]
This doesn't come under user knowledge since it's about using your IDE to compile a certain way. I suggest doing some Google research about the difference between a console application and a Windows application.
