### ISSUE TITLE
Noticeable Lag When Customizing a House

### ISSUE THREAD

**Issue by Iomega0318** [Pack4Duck/ClassicUO#1571]
**Describe the bug**
When customizing any house there is a noticeable lag/delay when placing each floor/wall/door etc. This does not happen on other clients I have tested, Orion, UOSteam, Classic, this is just with ClassicUO.

**To Reproduce**
1. Customize House
2. Place Items

**Shard**
 - All Shards

**Information (please complete the following information):**
 - OS: Win 10
 - ClassicUO Version: Latest
 - [ ] Using DEV Version? Tested with both release and dev version.
 - Launcher: ClassicUO Launcher

**Comment by andreakarasho** [comment]
https://github.com/ClassicUO/ClassicUO/pull/1717
