### ISSUE TITLE
Log in Issues with ClassicUO Launcher

### ISSUE THREAD

**Issue by TFidk** [Pack4Duck/ClassicUO#1586]
I set up my own Ultima Online Server (servuo) on my Synology NAS using a docker image, and the server is running. I can connect and play with the Enhanced Client and a launcher with no issues. However, I would like to use the ClassicUO client. However, I have a problem here that I can't find.

What have I done? I downloaded the latest Classic Client from the official UO homepage. Then the ClassicUO Launcher. I entered everything there (IP address, access data, etc.). I have a local IP address starting with 192.168.x.x and the IP address of the docker with 172.17.x.x.

When the window comes up where he fills in the pre-filled data (name/password) I click next and it then lists my shard in the server list. As soon as I select this, the "Log into server" window appears. It then remains in this window and does not continue. Based on the events displayed in the terminal, a disconnect is logged the moment I want to log on to the server. I was unable to locate the problem and find a solution to this. I hope that someone can help me here.

<a href="https://abload.de/image.php?img=login_stuckr3dv2.png"><img src="https://abload.de/img/login_stuckr3dv2.png" /></a>

<a href="https://abload.de/image.php?img=server_ip_listening_3cafwe.png"><img src="https://abload.de/img/server_ip_listening_3cafwe.png" /></a>

**Comment by ray77** [comment]
Did you try ClassicUO client release 0.1.7.0 ?
I have a similar issue connecting to RunUO.
https://github.com/ClassicUO/ClassicUO/issues/1584

**Comment by TFidk** [comment]
I haven't tested this version yet. Does this work? Where can i find the older version?

**Comment by ray77** [comment]
In my case it works. Would be very nice if you could test the 0.1.7.0. Because then it probably does not only affect RunUO.

**Comment by ray77** [comment]
https://github.com/ClassicUO/ClassicUO/releases/download/0.1.7.0/ClassicUO-beta-0-1-7-0-release.zip

**Comment by TFidk** [comment]
I have now tested versions 0.1.6.1 and 0.1.7.0. Unfortunately both of them don't work :(( Are there any alternatives? It's a shame. The enhanced client works, but it doesn't have the charm of the classic. I don't know if anyone can help with this problem either. :(

**Comment by roxya** [comment]
The disconnected message is normal/expected.

Can you enable packet logging in the ClassicUO launcher and show the generated network log?

![image](https://user-images.githubusercontent.com/7057924/216371527-57052d25-6523-4e96-93d6-7cc0eeb92d52.png)

**Comment by TFidk** [comment]
Hello and thank you for your answers. I activated the log and copied the content of the network log attached:


          Ticks: 1015 | Client -> Server |  ID: EF   Length: 21
          0  1  2  3  4  5  6  7   8  9  A  B  C  D  E  F
          -- -- -- -- -- -- -- --  -- -- -- -- -- -- -- --
00000000  EF 99 B2 A8 C0 00 00 00  07 00 00 00 00 00 00 00  ................
00000010  62 00 00 00 00                                    b....



          Ticks: 1015 | Client -> Server |  ID: 80   Length: 62
          [ACCOUNT CREDENTIALS HIDDEN]



          Ticks: 1068 | Server -> Client |  ID: A8   Length: 46
          0  1  2  3  4  5  6  7   8  9  A  B  C  D  E  F
          -- -- -- -- -- -- -- --  -- -- -- -- -- -- -- --
00000000  A8 00 2E 5D 00 01 00 00  52 65 74 72 6F 20 53 68  ...]....Retro Sh
00000010  61 72 64 00 00 00 00 00  00 00 00 00 00 00 00 00  ard.............
00000020  00 00 00 00 00 00 00 00  00 00 02 00 11 AC        ..............



          Ticks: 2309 | Client -> Server |  ID: A0   Length: 3
          0  1  2  3  4  5  6  7   8  9  A  B  C  D  E  F
          -- -- -- -- -- -- -- --  -- -- -- -- -- -- -- --
00000000  A0 00 00                                          ...



          Ticks: 2328 | Server -> Client |  ID: 8C   Length: 11
          0  1  2  3  4  5  6  7   8  9  A  B  C  D  E  F
          -- -- -- -- -- -- -- --  -- -- -- -- -- -- -- --
00000000  8C AC 11 00 02 0A 21 F7  01 B8 88                 ......!....



disconnection  -  socket_error: Success

**Comment by roxya** [comment]
Can you try with your local IP in the same subnet as the server?

**Comment by TFidk** [comment]
I tested it with the IP address 172.17.x.x. It can't find any servers (no shard) with this IP address. It also does not create a log with this connection. This is the internal Docker IP address. With 192.168.178.x he finds the shard but can't log in.

**Comment by TFidk** [comment]
I tested it with the IP address 172.17.x.x. It can't find any servers (no shard) with this IP address. It also does not create a log with this connection. This is the internal Docker IP address. With 192.168.178.x he finds the shard but can't log in. :(
The server is on the same subnet as the clients

**Comment by TFidk** [comment]
I found this. But I don't know how to actually do that. A file named "ServerListMap.xml" did not exist. Simply creating one and copying the content and storing it in the /config subdirectory didn't work. Have I perhaps overlooked something or a wrong procedure?

<a href="https://abload.de/image.php?img=uo_ip_translationzedig.png"><img src="https://abload.de/img/uo_ip_translationzedig.png" /></a>

**Comment by roxya** [comment]
That is a ServUO issue so not something we can help you with.

**Comment by TFidk** [comment]
These connection problems also seem to exist between ClassicUO and RunUO.  This is not an exclusive problem with servuo.

**Comment by TFidk** [comment]
> Did you try ClassicUO client release 0.1.7.0 ? I have a similar issue connecting to RunUO. #1584

I got it to work. The changes listed in the link must be made in the "ServerList.cs" and Scripts.csproj files. In addition, the "ServerListMap.xml" is created with the lines listed there. Adjust the IP address according to your circumstances. Recompile and start the server. Then the ClassicUO client worked without any problems.

https://github.com/ServUO/ServUO/pull/4955/files/b7360f2092ed829b2829d393531ea0f4312a805f
