### ISSUE TITLE
Ride-able Frostmites Beetles are not showing up in ClassicUO like they do in all other clients. 

### ISSUE THREAD

**Issue by tr1age** [Pack4Duck/ClassicUO#1587]
**Describe the bug**
Ride-able Frostmites Beetles are not showing up in ClassicUO like they do in all other clients. 
Client version: 7.0.98.0

**To Reproduce**
Spawn in one of the new ride-able Frostmites from OSI's version 7.0.98.0
Ride it. 
ClassicUO Assistant you cannot see it.
<img width="137" alt="image" src="https://user-images.githubusercontent.com/3319999/217397700-00c35930-6c80-4319-b597-58c09a6eff92.png">
Razor Alone or UOSteam:
<img width="144" alt="image" src="https://user-images.githubusercontent.com/3319999/217397826-52fb2995-100a-42ba-a59b-32b9e0021ed7.png">

**Expected behavior**
It should be visible in ClassicUO's launcher

**Screenshots**
Above

**Shard**
 - Name of the shard: UOAlive or OSI

**Information (please complete the following information):**
 - OS: Win 11
 - ClassicUO Version: Latest
 - [ NO ] Using DEV Version?
 - Launcher: ClassicUO Launcher

**Additional context**
 - How many clients do you run in parallel: 1
 - Screen Resolution: [e.g. 1920x1080] 4k

**Comment by andreakarasho** [comment]
do you have the anim id?

**Comment by tr1age** [comment]
base(name, 0x590, 0x3EDA,)

**Comment by andreakarasho** [comment]
added 9821a3fc0a7bfc7efc96926743ca8b50caf98e61

**Comment by tr1age** [comment]
So there is an animation now (thank you!) but it is not lined up properly it seems:

<img width="134" alt="image" src="https://user-images.githubusercontent.com/3319999/226203513-c33fd1b1-d883-4e47-bf76-254fd37a54a2.png">
<img width="121" alt="image" src="https://user-images.githubusercontent.com/3319999/226203522-a7f6002b-1590-45b3-b5ca-a892e751ec09.png">
<img width="144" alt="image" src="https://user-images.githubusercontent.com/3319999/226203525-2a815f3b-9d91-4ff9-bb01-de462a45e9b1.png">
<img width="138" alt="image" src="https://user-images.githubusercontent.com/3319999/226203526-a7509341-e3d6-48e7-9d11-4f1b6fe7ba55.png">
