### ISSUE TITLE
House Customization: Issue with Roof Tiles and an Extra Row of "Editing space" and "Supported tiles" on all custom houses.

### ISSUE THREAD

**Issue by tr1age** [Pack4Duck/ClassicUO#1588]
**Describe the bug**
House Customization: Issue with Roof Tiles and an Extra Row of "Editing space" on all custom houses.

- You get an extra row on the left and top end of custom houses in Classic UO Launcher that doesn't exist on any other client with the latest OSI house building in ServUO.

- Roof tiles that are placed and supported properly do not register as such and are labeled ORANGE instead of their hue when placed properly.

- Tiles that have no support and should not be allowed are being shown as allowed on ClassicUO Launcher when on Razor and other assistants they show as proper orange hue if not allowed. And can be commited.

- If you drag a tile over the same spot over and over it will think it is placing multiple tiles causing the cash to go up and total tiles used to max out, and will be stuck that way until you commit or leave customization an come back in.

**To Reproduce**
Videos
https://youtu.be/qmcW2rXJ-Ew - Roof Tiles and Extra row of tiles

https://youtu.be/KGzv-VknQcQ - Commitment issues (hehe), unsupported tile acceptance, and duplicate tiles

**Expected behavior**
video shows it all in both clients.

**Screenshots**
ClassicUOLauncher
<img width="382" alt="image" src="https://user-images.githubusercontent.com/3319999/217399369-d1d43e5b-4ffa-4054-8ea2-ac91d9a89ac7.png">
Razor Enhanced as it should be same customization 
<img width="454" alt="image" src="https://user-images.githubusercontent.com/3319999/217399460-a41bc597-4b41-4163-bda7-411338392cfc.png">

Extra tiles around the edges on ClassicUOLauncher
<img width="433" alt="image" src="https://user-images.githubusercontent.com/3319999/217399592-642ff73f-7983-47be-8ae1-bde09b36ff16.png">

Not acceptable support on Razor:
<img width="428" alt="image" src="https://user-images.githubusercontent.com/3319999/217399844-8cb774a7-b0c3-49a0-94e8-66d332a8e88c.png">

Classic UO Launcher thinking it is OK support:
<img width="415" alt="image" src="https://user-images.githubusercontent.com/3319999/217400000-9a5baa35-5953-4616-8b3c-cf52023931ac.png">

**Shard**
 - Name of the shard: UOAlive and OSI

**Information (please complete the following information):**
 - OS: Win 11
 - ClassicUO Version: Latest
 - [ No ] Using DEV Version?
 - Launcher: ClassicUO Launcher

**Additional context**
 - How many clients do you run in parallel: 1
 - Screen Resolution: [e.g. 1920x1080] 4k

**Comment by andreakarasho** [comment]
https://github.com/ClassicUO/ClassicUO/pull/1717
