### ISSUE TITLE
ProcessBodyDef

### ISSUE THREAD

**Issue by gabbus98** [Pack4Duck/ClassicUO#1589]
Trying to launch a Client using ClassicUO, but it won't start

Here is the log.
[2023-02-13_12-04-05_crash.txt](https://github.com/ClassicUO/ClassicUO/files/10721576/2023-02-13_12-04-05_crash.txt)

**Comment by andreakarasho** [comment]
Can you post your `body.def` file ?

**Comment by gabbus98** [comment]
Here it is, sorry but it's in italian ^^"
[Body.zip](https://github.com/ClassicUO/ClassicUO/files/10722919/Body.zip)

**Comment by gabbus98** [comment]
I noticed that at the row 354 there's a {?}
Maybe is it the problem?

**Comment by andreakarasho** [comment]
Yeah i think so, try to comment/remove that line and see what happen

**Comment by gabbus98** [comment]
Works perfectly! Thx a lot ^^
