### ISSUE TITLE
GumpSpriteImage does not display image

### ISSUE THREAD

**Issue by noobEone** [Pack4Duck/ClassicUO#1595]
**Describe the bug**
Server.Gumps.Gump
public void AddSpriteImage(int x, int y, int gumpID, int width, int height, int sx, int sy)
{
	Add(new GumpSpriteImage(x, y, gumpID, width, height, sx, sy));
}
^^^ This function does not display a partial image of gumpID as it does using the osi client.

OSI Client:
![image](https://user-images.githubusercontent.com/44480855/219965765-29794aa1-eee8-431d-8657-8ba4ad8fe0eb.png)

CUO:

![image](https://user-images.githubusercontent.com/44480855/219965896-01c9a620-7360-46e1-8302-a608446ea718.png)

**To Reproduce**
1.  Create a Mannequin in a house from a MannequinDeed.
2.  Click on Mannequin, "View Suit Stats With Item" -> Opens MannequinCompareGump

**Expected behavior**
Should see a bunch of icons pulled from a single image of sprites:
![image](https://user-images.githubusercontent.com/44480855/219966500-359d3775-c52d-4326-8ae9-6934bc456b77.png)

**Shard**
 - Name of the shard: UO Vanguard

**Information (please complete the following information):**
 - OS: win10
 - ClassicUO Version: 0.1.11.58
 - [ ] Using DEV Version? No
 - Launcher: classicuo_launcher

**Additional context**
 - How many clients do you run in parallel: 1
 - Screen Resolution: [1920x1080]

**Comment by SaschaKP** [comment]
can you attach the string that is sent by the server to the client?
it should be something like {{ buttontileart {0} {1} {2} {3} {4} {5} {6} {7} {8} {9} {10} }} (this is a mere example extracted from a runuo file)...

Since you have that specific file, you should send the string sent at the Compile() on the gump, this would allow to understand what is sent/received by the client.

That is also a gump.mul or an ART.mul file? or maybe you can use both?

**Comment by SaschaKP** [comment]
ok, found it on SERVUO:

return System.String.Format("{{ picinpic {0} {1} {2} {3} {4} {5} {6} }}", m_X, m_Y, m_GumpID, m_Width, m_Height, m_SX, m_SY);

public GumpSpriteImage(int x, int y, int gumpID, int width, int height, int sx, int sy)
		{
			m_X = x;
			m_Y = y;
			m_GumpID = gumpID;
			m_Width = width;
			m_Height = height;
			m_SX = sx;
			m_SY = sy;
		}

Edit: this makes things really strange, we have a piece of a pic inside a gump...I've already made some code, but couldn't test it, I'll pop a pull request
