### ISSUE TITLE
Crash while opening WorldMap

### ISSUE THREAD

**Issue by DemonRok** [Pack4Duck/ClassicUO#1602]
When I open the worldmap both from macro and from TopBar, CUO closes unexpectedly with the following error log

######################## [START LOG] ########################
ClassicUO [STANDARD_BUILD] - 0.1.11.59 - 03/03/2023 08:44:14
OS: Win32NT x64
Thread: CUO_MAIN_THREAD

Shard: localhost
ClientVersion: 7.0.0

Exception:
System.ArgumentNullException: Il valore non può essere null.
Nome parametro: data
   in Microsoft.Xna.Framework.Graphics.Texture2D.SetDataPointerEXT(Int32 level, Nullable`1 rect, IntPtr data, Int32 dataLength)
   in ClassicUO.Renderer.RenderedText.CreateTexture()
   in ClassicUO.Renderer.RenderedText.set_Text(String value)
   in ClassicUO.Renderer.RenderedText.Create(String text, UInt16 hue, Byte font, Boolean isunicode, FontStyle style, TEXT_ALIGN_TYPE align, Int32 maxWidth, Byte cell, Boolean isHTML, Boolean recalculateWidthByInfo, Boolean saveHitmap)
   in ClassicUO.Game.UI.Gumps.SystemChatControl.ChatLineTime..ctor(String text, Byte font, Boolean isunicode, UInt16 hue)
   in ClassicUO.Game.UI.Gumps.SystemChatControl.AddLine(String text, Byte font, UInt16 hue, Boolean isunicode)
   in ClassicUO.Game.UI.Gumps.SystemChatControl.ChatOnMessageReceived(Object sender, MessageEventArgs e)
   in System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   in ClassicUO.Utility.Exstentions.Raise[T](EventHandler`1 handler, T e, Object sender)
   in ClassicUO.Game.Managers.MessageManager.HandleMessage(Entity parent, String text, String name, UInt16 hue, MessageType type, Byte font, TextType textType, Boolean unicode, String lang)
   in ClassicUO.Game.GameActions.Print(Entity entity, String message, UInt16 hue, MessageType type, Byte font, Boolean unicode)
   in ClassicUO.Game.UI.Gumps.WorldMapGump..ctor()
   in ClassicUO.Game.GameActions.OpenWorldMap()
   in ClassicUO.Game.UI.Gumps.TopBarGump.OnButtonClick(Int32 buttonID)
   in ClassicUO.Game.UI.Controls.Button.OnMouseUp(Int32 x, Int32 y, MouseButtonType button)
   in ClassicUO.Game.UI.Gumps.TopBarGump.RighClickableButton.OnMouseUp(Int32 x, Int32 y, MouseButtonType button)
   in ClassicUO.Game.UI.Controls.Control.InvokeMouseUp(Point position, MouseButtonType button)
   in ClassicUO.Game.Managers.UIManager.OnMouseButtonUp(MouseButtonType button)
   in ClassicUO.GameController.HandleSdlEvent(IntPtr userData, IntPtr ptr)
   in SDL2.SDL.SDL_PollEvent(SDL_Event& _event)
   in Microsoft.Xna.Framework.SDL2_FNAPlatform.PollEvents(Game game, GraphicsAdapter& currentAdapter, Boolean[] textInputControlDown, Int32[] textInputControlRepeat, Boolean& textInputSuppress)
   in Microsoft.Xna.Framework.Game.RunLoop()
   in Microsoft.Xna.Framework.Game.Run()
   in ClassicUO.Client.Run()
   in ClassicUO.Bootstrap.Main(String[] args)

**Comment by DemonRok** [comment]
Additional logs in debug mode:

Nome parametro: data
   in Microsoft.Xna.Framework.Graphics.Texture2D.SetDataPointerEXT(Int32 level, Nullable`1 rect, IntPtr data, Int32 dataLength) in D:\GitHub\ClassicUO\external\FNA\src\Graphics\Texture2D.cs:riga 187
   in ClassicUO.Game.RenderedText.CreateTexture() in D:\GitHub\ClassicUO\src\ClassicUO.Client\Game\GameObjects\RenderedText.cs:riga 710
   in ClassicUO.Game.RenderedText.set_Text(String value) in D:\GitHub\ClassicUO\src\ClassicUO.Client\Game\GameObjects\RenderedText.cs:riga 143
   in ClassicUO.Game.RenderedText.Create(String text, UInt16 hue, Byte font, Boolean isunicode, FontStyle style, TEXT_ALIGN_TYPE align, Int32 maxWidth, Byte cell, Boolean isHTML, Boolean recalculateWidthByInfo, Boolean saveHitmap) in D:\GitHub\ClassicUO\src\ClassicUO.Client\Game\GameObjects\RenderedText.cs:riga 224
   in ClassicUO.Game.UI.Gumps.SystemChatControl.ChatLineTime..ctor(String text, Byte font, Boolean isunicode, UInt16 hue) in D:\GitHub\ClassicUO\src\ClassicUO.Client\Game\UI\Gumps\SystemChatControl.cs:riga 890
   in ClassicUO.Game.UI.Gumps.SystemChatControl.AddLine(String text, Byte font, UInt16 hue, Boolean isunicode) in D:\GitHub\ClassicUO\src\ClassicUO.Client\Game\UI\Gumps\SystemChatControl.cs:riga 354
   in ClassicUO.Game.UI.Gumps.SystemChatControl.ChatOnMessageReceived(Object sender, MessageEventArgs e) in D:\GitHub\ClassicUO\src\ClassicUO.Client\Game\UI\Gumps\SystemChatControl.cs:riga 252
   in System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   in ClassicUO.Utility.Exstentions.Raise[T](EventHandler`1 handler, T e, Object sender) in D:\GitHub\ClassicUO\src\ClassicUO.Utility\Extensions.cs:riga 56
   in ClassicUO.Game.Managers.MessageManager.HandleMessage(Entity parent, String text, String name, UInt16 hue, MessageType type, Byte font, TextType textType, Boolean unicode, String lang) in D:\GitHub\ClassicUO\src\ClassicUO.Client\Game\Managers\MessageManager.cs:riga 252
   in ClassicUO.Game.GameActions.Print(Entity entity, String message, UInt16 hue, MessageType type, Byte font, Boolean unicode) in D:\GitHub\ClassicUO\src\ClassicUO.Client\Game\GameActions.cs:riga 416
   in ClassicUO.Game.UI.Gumps.WorldMapGump..ctor() in D:\GitHub\ClassicUO\src\ClassicUO.Client\Game\UI\Gumps\WorldMapGump.cs:riga 133
   in ClassicUO.Game.GameActions.OpenWorldMap() in D:\GitHub\ClassicUO\src\ClassicUO.Client\Game\GameActions.cs:riga 196
   in ClassicUO.Game.UI.Gumps.TopBarGump.OnButtonClick(Int32 buttonID) in D:\GitHub\ClassicUO\src\ClassicUO.Client\Game\UI\Gumps\TopBarGump.cs:riga 332
   in ClassicUO.Game.UI.Controls.Button.OnMouseUp(Int32 x, Int32 y, MouseButtonType button) in D:\GitHub\ClassicUO\src\ClassicUO.Client\Game\UI\Controls\Button.cs:riga 295
   in ClassicUO.Game.UI.Gumps.TopBarGump.RighClickableButton.OnMouseUp(Int32 x, Int32 y, MouseButtonType button) in D:\GitHub\ClassicUO\src\ClassicUO.Client\Game\UI\Gumps\TopBarGump.cs:riga 388
   in ClassicUO.Game.UI.Controls.Control.InvokeMouseUp(Point position, MouseButtonType button) in D:\GitHub\ClassicUO\src\ClassicUO.Client\Game\UI\Controls\Control.cs:riga 556
   in ClassicUO.Game.Managers.UIManager.OnMouseButtonUp(MouseButtonType button) in D:\GitHub\ClassicUO\src\ClassicUO.Client\Game\Managers\UIManager.cs:riga 213
   in ClassicUO.GameController.HandleSdlEvent(IntPtr userData, IntPtr ptr) in D:\GitHub\ClassicUO\src\ClassicUO.Client\GameController.cs:riga 841
   in SDL2.SDL.SDL_PollEvent(SDL_Event& _event)
   in Microsoft.Xna.Framework.SDL2_FNAPlatform.PollEvents(Game game, GraphicsAdapter& currentAdapter, Boolean[] textInputControlDown, Int32[] textInputControlRepeat, Boolean& textInputSuppress) in D:\GitHub\ClassicUO\external\FNA\src\FNAPlatform\SDL2_FNAPlatform.cs:riga 792
   in Microsoft.Xna.Framework.Game.RunLoop() in D:\GitHub\ClassicUO\external\FNA\src\Game.cs:riga 864
   in Microsoft.Xna.Framework.Game.Run() in D:\GitHub\ClassicUO\external\FNA\src\Game.cs:riga 416
   in ClassicUO.Client.Run() in D:\GitHub\ClassicUO\src\ClassicUO.Client\Client.cs:riga 86
   in ClassicUO.Bootstrap.Main(String[] args) in D:\GitHub\ClassicUO\src\ClassicUO.Client\Main.cs:riga 249

Eccezione non gestita: System.ArgumentNullException: Il valore non può essere null.
Nome parametro: data
   in Microsoft.Xna.Framework.Graphics.Texture2D.SetDataPointerEXT(Int32 level, Nullable`1 rect, IntPtr data, Int32 dataLength) in D:\GitHub\ClassicUO\external\FNA\src\Graphics\Texture2D.cs:riga 187
   in ClassicUO.Game.RenderedText.CreateTexture() in D:\GitHub\ClassicUO\src\ClassicUO.Client\Game\GameObjects\RenderedText.cs:riga 710
   in ClassicUO.Game.RenderedText.set_Text(String value) in D:\GitHub\ClassicUO\src\ClassicUO.Client\Game\GameObjects\RenderedText.cs:riga 143
   in ClassicUO.Game.RenderedText.Create(String text, UInt16 hue, Byte font, Boolean isunicode, FontStyle style, TEXT_ALIGN_TYPE align, Int32 maxWidth, Byte cell, Boolean isHTML, Boolean recalculateWidthByInfo, Boolean saveHitmap) in D:\GitHub\ClassicUO\src\ClassicUO.Client\Game\GameObjects\RenderedText.cs:riga 224
   in ClassicUO.Game.UI.Gumps.SystemChatControl.ChatLineTime..ctor(String text, Byte font, Boolean isunicode, UInt16 hue) in D:\GitHub\ClassicUO\src\ClassicUO.Client\Game\UI\Gumps\SystemChatControl.cs:riga 890
   in ClassicUO.Game.UI.Gumps.SystemChatControl.AddLine(String text, Byte font, UInt16 hue, Boolean isunicode) in D:\GitHub\ClassicUO\src\ClassicUO.Client\Game\UI\Gumps\SystemChatControl.cs:riga 354
   in ClassicUO.Game.UI.Gumps.SystemChatControl.ChatOnMessageReceived(Object sender, MessageEventArgs e) in D:\GitHub\ClassicUO\src\ClassicUO.Client\Game\UI\Gumps\SystemChatControl.cs:riga 252
   in System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   in ClassicUO.Utility.Exstentions.Raise[T](EventHandler`1 handler, T e, Object sender) in D:\GitHub\ClassicUO\src\ClassicUO.Utility\Extensions.cs:riga 56
   in ClassicUO.Game.Managers.MessageManager.HandleMessage(Entity parent, String text, String name, UInt16 hue, MessageType type, Byte font, TextType textType, Boolean unicode, String lang) in D:\GitHub\ClassicUO\src\ClassicUO.Client\Game\Managers\MessageManager.cs:riga 252
   in ClassicUO.Game.GameActions.Print(Entity entity, String message, UInt16 hue, MessageType type, Byte font, Boolean unicode) in D:\GitHub\ClassicUO\src\ClassicUO.Client\Game\GameActions.cs:riga 416
   in ClassicUO.Game.UI.Gumps.WorldMapGump..ctor() in D:\GitHub\ClassicUO\src\ClassicUO.Client\Game\UI\Gumps\WorldMapGump.cs:riga 133
   in ClassicUO.Game.GameActions.OpenWorldMap() in D:\GitHub\ClassicUO\src\ClassicUO.Client\Game\GameActions.cs:riga 196
   in ClassicUO.Game.UI.Gumps.TopBarGump.OnButtonClick(Int32 buttonID) in D:\GitHub\ClassicUO\src\ClassicUO.Client\Game\UI\Gumps\TopBarGump.cs:riga 332
   in ClassicUO.Game.UI.Controls.Button.OnMouseUp(Int32 x, Int32 y, MouseButtonType button) in D:\GitHub\ClassicUO\src\ClassicUO.Client\Game\UI\Controls\Button.cs:riga 295
   in ClassicUO.Game.UI.Gumps.TopBarGump.RighClickableButton.OnMouseUp(Int32 x, Int32 y, MouseButtonType button) in D:\GitHub\ClassicUO\src\ClassicUO.Client\Game\UI\Gumps\TopBarGump.cs:riga 388
   in ClassicUO.Game.UI.Controls.Control.InvokeMouseUp(Point position, MouseButtonType button) in D:\GitHub\ClassicUO\src\ClassicUO.Client\Game\UI\Controls\Control.cs:riga 556
   in ClassicUO.Game.Managers.UIManager.OnMouseButtonUp(MouseButtonType button) in D:\GitHub\ClassicUO\src\ClassicUO.Client\Game\Managers\UIManager.cs:riga 213
   in ClassicUO.GameController.HandleSdlEvent(IntPtr userData, IntPtr ptr) in D:\GitHub\ClassicUO\src\ClassicUO.Client\GameController.cs:riga 841
   in SDL2.SDL.SDL_PollEvent(SDL_Event& _event)
   in Microsoft.Xna.Framework.SDL2_FNAPlatform.PollEvents(Game game, GraphicsAdapter& currentAdapter, Boolean[] textInputControlDown, Int32[] textInputControlRepeat, Boolean& textInputSuppress) in D:\GitHub\ClassicUO\external\FNA\src\FNAPlatform\SDL2_FNAPlatform.cs:riga 792
   in Microsoft.Xna.Framework.Game.RunLoop() in D:\GitHub\ClassicUO\external\FNA\src\Game.cs:riga 864
   in Microsoft.Xna.Framework.Game.Run() in D:\GitHub\ClassicUO\external\FNA\src\Game.cs:riga 416
   in ClassicUO.Client.Run() in D:\GitHub\ClassicUO\src\ClassicUO.Client\Client.cs:riga 86
   in ClassicUO.Bootstrap.Main(String[] args) in D:\GitHub\ClassicUO\src\ClassicUO.Client\Main.cs:riga 249

**Comment by DemonRok** [comment]
The problem is not related to the version, but to the management of the World Map.
Despite the presence of the gumpartLegacyMUL.uop file, ClassicUO looks for the outline graphics in the Gumpart.mul file.
In my opinion this is an unnecessary redundancy.

**Comment by roxya** [comment]
Which graphics are you talking about? The crash is related to text generation. Are you sure you want to close it?

**Comment by DemonRok** [comment]
I thought I understood that it was my problem. But even restoring the files from the shard that I had tried to edit still doesn't work

**Comment by andreakarasho** [comment]
Fixed 66037aa30eecb67052a2f8c7ab5ff5b47113bb78
