### ISSUE TITLE
Cannot Customize Houses at all.

### ISSUE THREAD

**Issue by Dramoor** [Pack4Duck/ClassicUO#1604]
You cannot use the house customization gump at all since the last update.  While the gump is shown on screen, no interaction can be done with it and the client is treating it as if it is not there. Pretty much makes any sort of house customizing out of the use of CUO and forces us to re-open OSI client to do so.

**To Reproduce**
1. Go to your house. Enter customization mode.

**Expected behavior**
To be able to use the menu to build your house.

**Screenshots**

**Shard**
Should be any server.

**Information (please complete the following information):**
 - OS: Win 10
 - ClassicUO Version: 0.1.11.0
 - [ ] Using DEV Version?  Main Version on Git.
 - Launcher: Using from Github main.

**Comment by andreakarasho** [comment]
fixed edae3dabe339965a4b258b1ace94280a7f0733d2
