### ISSUE TITLE
mac version of client crashes

### ISSUE THREAD

**Issue by Yukimimiya** [Pack4Duck/ClassicUO#1627]
**Describe the bug**
mac version of client crashes. 

**To Reproduce**
1. Download client from https://www.classicuo.eu/
2. install zlib using brew.
3. unzip ClassicUOLauncher-osx-x64-release.zip
4. mv ClassicUOLauncher.app /Applications
5. Launch ClassicUOLauncher.app

**Expected behavior**
Application should be launched.

**Error**
I attached crash report.
[Crash-Report.txt](https://github.com/ClassicUO/ClassicUO/files/11847988/Crash-Report.txt)

**Information (please complete the following information):**
 - OS: macOS Ventura 13.4.1
 - Intel Mac (Mac mini - Intel Core i7)

**Comment by jimpodroskey** [comment]
I'm having a similar issue.

OSX: 14.2.1 (23C71)
Apple M3 Pro

**Comment by andreakarasho** [comment]
Should be fixed
