### ISSUE TITLE
Publish custom version

### ISSUE THREAD

**Issue by gabbus98** [Pack4Duck/ClassicUO#1646]
Hi all,
I'm trying to publish/release a custom version but... After i did all the changes need and tested it on an online server where i'm currently playing, i'm having difficulties 'cause i truly don't know *how* release the updated version.
Some months ago i managed to do it, but now my memory is white.
I tryed to use the "build.cmd" inside scripts, but it looks for a ".csproj" that i don't have t-t

**Comment by bittiez** [comment]
`cd ClassicUO repo folder`
`build dotnet -c Release`

Look in bin/Release folder

**Comment by gabbus98** [comment]
Ok, it generates 34 elements, but if i remember right, there's a way to generate less, to make it more compact

**Comment by bittiez** [comment]
There are ways but they aren't as easy as this, you'll need to do some research on how to do it. A good place to start would be here: https://learn.microsoft.com/en-us/dotnet/core/deploying/single-file/overview?tabs=cli
