### ISSUE TITLE
Launcher crashes on Mac with Error EXC_BAD_ACCESS (SIGSEGV)

### ISSUE THREAD

**Issue by Traace** [Pack4Duck/ClassicUO#1685]
**Describe the bug**
ClassicUO Launcher opens but crashes after creating a new profile. Therefore I'm unable to launch the game

**To Reproduce**
1. Drop Launcher to /Applications
1. Launch the Launcher
2. Click on 'Create your first profile'
2. Click on 'Add'
4. Set OU path
5. Get a application crash without a profile save

**Expected behavior**
The Launcher shall save the path properly and shall not crash...

**Screenshots**
[Log.txt](https://github.com/user-attachments/files/16063658/Log.txt)

**Shard**
 - Name of the shard: Outlands

**Information (please complete the following information):**
 - OS: MacOS 15.0
 - ClassicUO Version: 7.0.24.0
 - Using DEV Version? No
 - Launcher: classicuo_launcher
 - Full Disk Access: Granted

**Additional context**
 - How many clients do you run in parallel: 1
 - Screen Resolution: 5120x2880

**Comment by andreakarasho** [comment]
A new launcher update which should fix the issue has been deployed
