### ISSUE TITLE
Malware warning BitDefender Total Security

### ISSUE THREAD

**Issue by Desadius** [Pack4Duck/ClassicUO#1698]
![image](https://github.com/user-attachments/assets/33eac600-e209-41c4-9d1a-1ac6717aae97)

downloaded from github link is this normal?

**Comment by Desadius** [comment]
https://www.classicuo.eu/launcher/win-x64/ClassicUOLauncher-win-x64-release.zip

**Comment by andreakarasho** [comment]
It's a false positive and should be fine now
